### ISSUE TITLE
issue updating to v6

### ISSUE THREAD

**Issue by jdx** [heroku/cli-engine#16]
What is happening here is the 5.x release successfully updates to v6 (probably), but it then tries to update the plugins and fails there.

```
$ heroku update v6
heroku-cli: Updating to 5.99.0-9069be3... (v6) 2.07 MB/2.07 MB
heroku-cli: Updating heroku-redis... !
 ▸    module.js:442
 ▸        throw err;
 ▸        ^
 ▸
 ▸    Error: Cannot find module '/Users/mgauger/.local/share/heroku/cli/lib/npm/cli.js'
 ▸        at Function.Module._resolveFilename (module.js:440:15)
 ▸        at Function.Module._load (module.js:388:25)
 ▸        at Module.runMain (module.js:575:10)
 ▸        at run (node.js:348:7)
 ▸        at startup (node.js:140:9)
 ▸        at node.js:463:3
heroku-cli: Updating heroku-sudo... !
 ▸    module.js:442
 ▸        throw err;
 ▸        ^
 ▸
 ▸    Error: Cannot find module '/Users/mgauger/.local/share/heroku/cli/lib/npm/cli.js'
 ▸        at Function.Module._resolveFilename (module.js:440:15)
 ▸        at Function.Module._load (module.js:388:25)
 ▸        at Module.runMain (module.js:575:10)
 ▸        at run (node.js:348:7)
 ▸        at startup (node.js:140:9)
 ▸        at node.js:463:3
heroku-cli: Updating heroku-cli-static... !
 ▸    module.js:442
 ▸        throw err;
 ▸        ^
 ▸
 ▸    Error: Cannot find module '/Users/mgauger/.local/share/heroku/cli/lib/npm/cli.js'
 ▸        at Function.Module._resolveFilename (module.js:440:15)
 ▸        at Function.Module._load (module.js:388:25)
 ▸        at Module.runMain (module.js:575:10)
 ▸        at run (node.js:348:7)
 ▸        at startup (node.js:140:9)
 ▸        at node.js:463:3
heroku-cli: Updating heroku-event-log... !
 ▸    module.js:442
 ▸        throw err;
 ▸        ^
 ▸
 ▸    Error: Cannot find module '/Users/mgauger/.local/share/heroku/cli/lib/npm/cli.js'
 ▸        at Function.Module._resolveFilename (module.js:440:15)
 ▸        at Function.Module._load (module.js:388:25)
 ▸        at Module.runMain (module.js:575:10)
 ▸        at run (node.js:348:7)
 ▸        at startup (node.js:140:9)
 ▸        at node.js:463:3
heroku-cli: Updating heroku-cli-oauth... !
 ▸    module.js:442
 ▸        throw err;
 ▸        ^
 ▸
 ▸    Error: Cannot find module '/Users/mgauger/.local/share/heroku/cli/lib/npm/cli.js'
 ▸        at Function.Module._resolveFilename (module.js:440:15)
 ▸        at Function.Module._load (module.js:388:25)
 ▸        at Module.runMain (module.js:575:10)
 ▸        at run (node.js:348:7)
 ▸        at startup (node.js:140:9)
 ▸        at node.js:463:3
heroku-cli: Updating heroku-api-plugin... !
 ▸    module.js:442
 ▸        throw err;
 ▸        ^
 ▸
 ▸    Error: Cannot find module '/Users/mgauger/.local/share/heroku/cli/lib/npm/cli.js'
 ▸        at Function.Module._resolveFilename (module.js:440:15)
 ▸        at Function.Module._load (module.js:388:25)
 ▸        at Module.runMain (module.js:575:10)
 ▸        at run (node.js:348:7)
 ▸        at startup (node.js:140:9)
 ▸        at node.js:463:3
heroku-cli: Updating heroku-splunk... !
 ▸    module.js:442
 ▸        throw err;
 ▸        ^
 ▸
 ▸    Error: Cannot find module '/Users/mgauger/.local/share/heroku/cli/lib/npm/cli.js'
 ▸        at Function.Module._resolveFilename (module.js:440:15)
 ▸        at Function.Module._load (module.js:388:25)
 ▸        at Module.runMain (module.js:575:10)
 ▸        at run (node.js:348:7)
 ▸        at startup (node.js:140:9)
 ▸        at node.js:463:3
heroku-cli: Updating plugins... done
```

**Comment by garyposter** [comment]
@dickeyxxx intends to look at this when he returns

**Comment by RasPhilCo** [comment]
@dickeyxxx What if we [remove the plugins update](https://github.com/heroku/cli/blob/8fd1929b0dab5e12e22fbce70d0150308f4f7f33/update.go#L52) from `5.99` as `6.x` will migrate and update them on first run?

**Comment by jdx** [comment]
It's not in 5.99, look at the 5.99 branch

**Comment by RasPhilCo** [comment]
@dickeyxxx you know, I would of swore to you  I was on `5.99` when I looked at `update.go`... ok hmm...

**Comment by RasPhilCo** [comment]
For context: On `upgrade v6`, `v5.7` calls `updateCLI` & then `UserPlugins.Update`. However, on `updateCLI`, `v5.99` removes the dir `.local/share/heroku/cli/lib/npm`, so when `UserPlugins.Update` is called a few lines later, it errors with `Cannot find module '/Users/user/.local/share/heroku/cli/lib/npm/cli.js'`.

So, I think, we can do 1 of these:
1) Not delete `local/share/heroku/cli/lib/npm` in `v5.99`
2) Not call `UserPlugins.Update` if cli update manifest is `v5.99`
2) Guard/check for the presence of npm packages  in top of `UserPlugins.Update`

**Comment by jdx** [comment]
Sorry @rasphilco for not explaining more at the time, but yeah, what you described is the issue. Maybe we could just do the plugin update before updating the CLI in v5.x?

**Comment by jdx** [comment]
@RasPhilCo see https://github.com/heroku/cli/commit/412bcd0b46a4d83523bb562b7dbb8ac93c7e0c39
