### ISSUE TITLE
`run` appears to fail with `Invalid listen argument: [object Object]`

### ISSUE THREAD

**Issue by cdwort** [heroku/cli-engine#33]
I'm on V6 `heroku-cli/6.4.6-e6a8ec6 v6 (darwin-x64) node-v7.7.2`

Output without debug (first time had duplicate statements, second time not). Assorted data redacted:
```
$ heroku run rake db:migrate -a my-app
Running rake db:migrate on ⬢ my-app... ⣷
Running rake db:migrate on ⬢ my-app... starting, run.9061 (Private-M)
 ▸    Warning: Dynos can take up to a few minutes to be provisioned in Private Spaces.
 ▸    Invalid listen argument: [object Object]
➜ ~/…/addons.heroku.com $ heroku run rake db:migrate -a my-app
Running rake db:migrate on ⬢ my-app... starting, run.1914 (Private-M)
 ▸    Warning: Dynos can take up to a few minutes to be provisioned in Private Spaces.
 ▸    Invalid listen argument: [object Object]
```

Output with debug:
```
$ HEROKU_DEBUG=1 heroku run bash -a my-app
Exiting with code: 0
--> POST /apps/my-app/dynos
--> {"command":"bash","attach":true,"env":{"TERM":"xterm-256color","COLUMNS":254,"LINES":61}}
Running bash on ⬢ my-app... ⣯
 ▸    Warning: Dynos can take up to a few minutes to be provisioned in Private Spaces.
<-- 201 Created
<-- {"attach_url":"https://user-UUID:TOKEN=@proxy.stormy-ravine-9142.herokuspace.com/session/session-UUID","command":"bash","created_at":"0001-01-01T00:00:00Z","id":"7a8891c3-8026-4d63-b85c-c71f531ea049","name":"run.2182","app":{"id":"app-UUID","name":"my-app"},"release":{"id":"release-UUID","version":556},"size":"Private-M","state":"provisioning","type":"run","updated_at":"0001-⡿1-01T00:00:00Z"}
--> GET /apps/my-app/dynos/run.2182
<-- 404 Not Found                      ⣾
<-- {"resource":"dyno","id":"not_found"⣾"message":"Couldn't find that dyno."}
--> GET /apps/my-app/dynos/run.2182
<-- 200 OK
Running bash on ⬢ my-app... starting, run.2182 (Private-M)
 ▸    Warning: Dynos can take up to a few minutes to be provisioned in Private Spaces.
Error: Invalid listen argument: [object Object]
    at Server.listen (net.js:1418:9)
    at ClientRequest.r.on (/Users/aunger/.local/share/heroku-cli/cli/node_modules/heroku-run/lib/dyno.js:155:11)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:197:7)
    at TLSSocket.socketOnData (_http_client.js:443:11)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:563:20)
Exiting with code: 1
```

**Comment by jdx** [comment]
likely due to the updated node version
