### ISSUE TITLE
Need to rebuild after update for node bumps

### ISSUE THREAD

**Issue by ransombriggs** [heroku/cli-engine#53]

**Comment by jdx** [comment]
note that we won't really need this until we want to bump node with a new v8 version

**Comment by ransombriggs** [comment]
@dickeyxxx users (with heroku-kafka) who are on a v5 / node6 version who skip straight to v6 / node7 would have issues, not sure how much of an issue this would be

**Comment by jdx** [comment]
you're correct it would be an issue

**Comment by jdx** [comment]
`yarn install --force`

**Comment by ransombriggs** [comment]
@dickeyxxx I was going to try using `yarn install --force` but it turns out that our upgrade procedure for the plugins actually causes `heroku kakfa` to rebuild, see `[4/4] 📃  Rebuilding all packages...`  We still get `was compiled against a different Node.js version` which is coming from the command cache reloading I believe, do you want me to see if I can suppress that?  This is much better than before it that it heals itself without our intervention.
```
-> % HEROKU_DEBUG=1 heroku update beta
heroku-cli/5.6.24-dbb4f5d (darwin-amd64) go1.7.4 /usr/local/lib/heroku/bin/heroku cmd: update
heroku-cli: Updating to 5.99.0-68be08e... (beta) 2.07 MB/2.07 MB
updated to 5.99.0-68be08e
Executing /Users/rbriggs/.local/share/heroku/cli/bin/heroku
heroku-cli: Updating to 6.6.7-c986b6f... (beta) 11.1 MB/11.1 MB
updated to 6.6.7-c986b6f
Migrating V5 plugins...
Adding to plugins pjson: heroku-kafka
heroku-cli: Updating CLI...
--> GET https://cli-assets.heroku.com/heroku-cli/channels/beta/darwin-x64
<-- GET https://cli-assets.heroku.com/heroku-cli/channels/beta/darwin-x64 200
updating cache for /Users/rbriggs/.local/share/heroku/plugins/node_modules/heroku-kafka
WARNING: Error: The module '/Users/rbriggs/.local/share/heroku/plugins/node_modules/snappy/build/Release/binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/rbriggs/.local/share/heroku/plugins/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/rbriggs/.local/share/heroku/plugins/node_modules/snappy/snappy.js:1:96)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/rbriggs/.local/share/heroku/plugins/node_modules/no-kafka/lib/protocol/misc/compression.js:4:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
--> POST https://cli-analytics.heroku.com/record
<-- POST https://cli-analytics.heroku.com/record 201
updating cache for /Users/rbriggs/.local/share/heroku/plugins/node_modules/heroku-kafka
WARNING: Error: The module '/Users/rbriggs/.local/share/heroku/plugins/node_modules/snappy/build/Release/binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/rbriggs/.local/share/heroku/plugins/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/rbriggs/.local/share/heroku/plugins/node_modules/snappy/snappy.js:1:96)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/rbriggs/.local/share/heroku/plugins/node_modules/no-kafka/lib/protocol/misc/compression.js:4:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
heroku-cli: Updating plugins...
/Users/rbriggs/.local/share/heroku/plugins: /Users/rbriggs/.local/share/heroku/client/node_modules/cli-engine/yarn/yarn-0.23.3.js 
yarn install v0.23.3
info No lockfile found.
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 4.53s.
/Users/rbriggs/.local/share/heroku/plugins: /Users/rbriggs/.local/share/heroku/client/node_modules/cli-engine/yarn/yarn-0.23.3.js upgrade
yarn upgrade v0.23.3
warning package.json: No license field
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Rebuilding all packages...
success Saved lockfile.
success Saved 193 new dependencies.
├─ abbrev@1.1.0
├─ ajv@4.11.8
├─ ansi-escapes@1.4.0
├─ ansi-regex@2.1.1
├─ ansi-styles@2.2.1
├─ ansicolors@0.2.1
├─ aproba@1.1.1
├─ are-we-there-yet@1.1.4
├─ array-index@1.0.0
├─ asn1@0.2.3
├─ assert-plus@1.0.0
├─ asynckit@0.4.0
├─ aws-sign2@0.6.0
├─ aws4@1.6.0
├─ balanced-match@0.4.2
├─ bcrypt-pbkdf@1.0.1
├─ bin-protocol@3.0.3
├─ bindings@1.2.1
├─ block-stream@0.0.9
├─ bluebird@3.5.0
├─ boom@2.10.1
├─ brace-expansion@1.1.7
├─ buffer-crc32@0.2.13
├─ buffer-shims@1.0.0
├─ capture-stack-trace@1.0.0
├─ cardinal@0.7.1
├─ caseless@0.12.0
├─ chalk@1.1.3
├─ co-wait@0.0.0
├─ co@4.6.0
├─ code-point-at@1.1.0
├─ combined-stream@1.0.5
├─ concat-map@0.0.1
├─ connection-parse@0.0.7
├─ console-control-strings@1.1.0
├─ core-util-is@1.0.2
├─ create-error-class@3.0.2
├─ cryptiles@2.0.5
├─ d@1.0.0
├─ dashdash@1.14.1
├─ debug@2.2.0
├─ delayed-stream@1.0.0
├─ delegates@1.0.0
├─ duplexer3@0.1.4
├─ ecc-jsbn@0.1.1
├─ es5-ext@0.10.18
├─ es6-iterator@2.0.1
├─ es6-symbol@3.1.1
├─ escape-string-regexp@1.0.5
├─ esprima@2.7.3
├─ extend@3.0.1
├─ extsprintf@1.0.2
├─ forever-agent@0.6.1
├─ form-data@2.1.4
├─ fs.realpath@1.0.0
├─ fstream@1.0.11
├─ gauge@2.6.0
├─ get-stream@3.0.0
├─ getpass@0.1.7
├─ glob@7.1.1
├─ got@6.7.1
├─ graceful-fs@4.1.11
├─ har-schema@1.0.5
├─ har-validator@4.2.1
├─ has-ansi@2.0.0
├─ has-color@0.1.7
├─ has-flag@1.0.0
├─ has-unicode@2.0.1
├─ hashring@3.2.0
├─ hawk@3.1.3
├─ heroku-cli-addons@1.0.5
├─ heroku-cli-util@6.0.15
├─ heroku-client@3.0.0-beta3
├─ heroku-kafka@2.9.2
├─ hoek@2.16.3
├─ http-signature@1.1.1
├─ humanize-plus@1.8.2
├─ inflight@1.0.6
├─ inherits@2.0.3
├─ is-fullwidth-code-point@1.0.0
├─ is-redirect@1.0.0
├─ is-retry-allowed@1.1.0
├─ is-stream@1.1.0
├─ is-typedarray@1.0.0
├─ isarray@1.0.0
├─ isexe@2.0.0
├─ isstream@0.1.2
├─ jodid25519@1.0.2
├─ jsbn@0.1.1
├─ json-schema@0.2.3
├─ json-stable-stringify@1.0.1
├─ json-stringify-safe@5.0.1
├─ jsonify@0.0.0
├─ jsprim@1.4.0
├─ lodash._baseclone@4.5.7
├─ lodash._baseeach@4.1.3
├─ lodash._baseflatten@4.2.1
├─ lodash._basefor@3.0.3
├─ lodash._baseiteratee@4.7.0
├─ lodash._basetostring@4.12.0
├─ lodash._createwrapper@4.0.5
├─ lodash._root@3.0.1
├─ lodash._stringtopath@4.8.0
├─ lodash.ary@4.1.0
├─ lodash.assigninwith@4.2.0
├─ lodash.defaults@4.1.0
├─ lodash.get@4.4.0
├─ lodash.groupby@4.4.0
├─ lodash.identity@3.0.0
├─ lodash.isplainobject@4.0.6
├─ lodash.keys@4.0.8
├─ lodash.keysin@4.2.0
├─ lodash.mapvalues@4.5.0
├─ lodash.memoize@4.1.0
├─ lodash.merge@4.4.0
├─ lodash.noop@3.0.1
├─ lodash.partial@4.2.0
├─ lodash.pickby@4.5.0
├─ lodash.property@4.4.0
├─ lodash.repeat@4.0.4
├─ lodash.rest@4.0.5
├─ lodash.result@4.5.0
├─ lodash.some@4.4.0
├─ lodash.sortby@4.5.0
├─ lodash.topairs@4.1.1
├─ lodash.tostring@4.1.4
├─ lodash.uniqby@4.6.1
├─ lodash.values@4.1.0
├─ lodash@4.17.4
├─ long@3.2.0
├─ lowercase-keys@1.0.0
├─ mime-db@1.27.0
├─ mime-types@2.1.15
├─ minimatch@3.0.4
├─ minimist@0.0.8
├─ mkdirp@0.5.1
├─ ms@0.7.1
├─ nan@2.3.5
├─ nice-simple-logger@1.0.1
├─ no-kafka@2.4.1
├─ node-gyp@3.4.0
├─ node-spinner@0.0.4
├─ nopt@3.0.6
├─ npmlog@3.1.2
├─ number-is-nan@1.0.1
├─ oauth-sign@0.8.2
├─ object-assign@4.1.1
├─ once@1.4.0
├─ opn@3.0.3
├─ os-homedir@1.0.2
├─ os-tmpdir@1.0.2
├─ osenv@0.1.4
├─ path-array@1.0.1
├─ path-is-absolute@1.0.1
├─ performance-now@0.2.0
├─ prepend-http@1.0.4
├─ printf@0.2.5
├─ process-nextick-args@1.0.7
├─ protocol-buffers-schema@3.3.1
├─ punycode@1.4.1
├─ qs@6.4.0
├─ readable-stream@2.2.9
├─ redeyed@0.6.0
├─ request@2.81.0
├─ rimraf@2.6.1
├─ safe-buffer@5.0.1
├─ semver@5.3.0
├─ set-blocking@2.0.0
├─ signal-exit@3.0.2
├─ simple-lru-cache@0.0.2
├─ snappy@5.0.5
├─ sntp@1.0.9
├─ sshpk@1.13.0
├─ string_decoder@1.0.0
├─ string-width@1.0.2
├─ stringstream@0.0.5
├─ strip-ansi@3.0.1
├─ supports-color@3.2.3
├─ tar@2.2.1
├─ timed-out@4.0.1
├─ tough-cookie@2.3.2
├─ tunnel-agent@0.4.3
├─ tweetnacl@0.14.5
├─ unzip-response@2.0.1
├─ url-parse-lax@1.0.0
├─ util-deprecate@1.0.2
├─ util-extend@1.0.3
├─ uuid@3.0.1
├─ verror@1.3.6
├─ which@1.2.14
├─ wide-align@1.1.2
├─ wrappy@1.0.2
└─ wrr-pool@1.1.3
warning No license field
✨  Done in 6.10s.
Clearing cache for /Users/rbriggs/.local/share/heroku/plugins/node_modules/heroku-kafka
Exiting with code: 0
rbriggs@ebriggs-ltm [15:29:59] [~/.local/share] 
-> % 
```

**Comment by jdx** [comment]
yeah looks good, last week I was looking at refactoring the plugin loading a bit to get around errors like this but this should be fine to fix this problem

**Comment by garyposter** [comment]
Heroku Kafka uses a native dependency, so moving to a new version of Node breaks Kafka.

**Comment by ransombriggs** [comment]
Fix released in https://github.com/heroku/cli-engine/pull/188
