### ISSUE TITLE
updates do not work on windows

### ISSUE THREAD

**Issue by jdx** [heroku/cli-engine#86]
<img width="1082" alt="screen shot 2017-04-26 at 6 04 03 pm" src="https://cloud.githubusercontent.com/assets/216188/25463403/d52c6aee-2aaa-11e7-9f85-cf6f72213599.png">

**Comment by ransombriggs** [comment]
I have the 32 bit version of the CLI installed from debugging that user issue and it bails after update
```
IEUser@IE11Win7 MINGW32 ~
$ heroku
 !    HTTP Error: http://cli-assets.heroku.com/heroku-cli/channels/beta/win32-386 404 Not Found

IEUser@IE11Win7 MINGW32 ~
```

**Comment by ransombriggs** [comment]
Put together a PR for 32 bit fixes here https://github.com/heroku/cli/pull/455

**Comment by ransombriggs** [comment]
```
Error: EPERM: operation not permitted, unlink 'C:\Users\IEUser\AppData\Local\heroku\client\bin\node.exe'
    at Object.fs.unlinkSync (fs.js:1081:18)
    at fixWinEPERMSync (C:\Users\IEUser\AppData\Local\heroku\client\node_modules\fs-extra\lib\remove\rimraf.js:169:13)
    at rimrafSync (C:\Users\IEUser\AppData\Local\heroku\client\node_modules\fs-extra\lib\remove\rimraf.js:260:26)
    at options.readdirSync.forEach.f (C:\Users\IEUser\AppData\Local\heroku\client\node_modules\fs-extra\lib\remove\rimraf.js:291:39)
    at Array.forEach (native)
    at rmkidsSync (C:\Users\IEUser\AppData\Local\heroku\client\node_modules\fs-extra\lib\remove\rimraf.js:291:26)
    at rmdirSync (C:\Users\IEUser\AppData\Local\heroku\client\node_modules\fs-extra\lib\remove\rimraf.js:283:7)
    at fixWinEPERMSync (C:\Users\IEUser\AppData\Local\heroku\client\node_modules\fs-extra\lib\remove\rimraf.js:167:5)
    at rimrafSync (C:\Users\IEUser\AppData\Local\heroku\client\node_modules\fs-extra\lib\remove\rimraf.js:260:26)
    at options.readdirSync.forEach.f (C:\Users\IEUser\AppData\Local\heroku\client\node_modules\fs-extra\lib\remove\rimraf.js:291:39)
Exiting with code: 1
The batch file cannot be found.
```

**Comment by ransombriggs** [comment]
Fix for windows updates here https://github.com/heroku/cli-engine/pull/91
